export const ADMIN_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CLONE: 'CLONE',
  ARCHIVE: 'ARCHIVE',
  PUBLISH: 'PUBLISH',
  UNPUBLISH: 'UNPUBLISH',
  MOVE: 'MOVE',
  UPDATE_TAGS: 'UPDATE_TAGS',
  BULK_DELETE: 'BULK_DELETE',
  BULK_ARCHIVE: 'BULK_ARCHIVE',
  BULK_PUBLISH: 'BULK_PUBLISH',
  BULK_UNPUBLISH: 'BULK_UNPUBLISH',
  BULK_MOVE: 'BULK_MOVE',
  BULK_UPDATE_TAGS: 'BULK_UPDATE_TAGS',
  IMPORT_CSV: 'IMPORT_CSV',
  REORDER: 'REORDER'
};

export const ENTITY_TYPES = {
  SHEET: 'Sheet',
  SUBJECT: 'Subject',
  CHAPTER: 'Chapter',
  RESOURCE: 'Resource'
};
