export const RECOMMENDATION_TYPES = {
  CONTINUE_STAGE: 'CONTINUE_STAGE',
  START_NEXT_CHAPTER: 'START_NEXT_CHAPTER',
  REVISE_OVERDUE: 'REVISE_OVERDUE',
  FINISH_PENDING: 'FINISH_PENDING',
};

export const TIMELINE_EVENT_TYPES = {
  RESOURCE_VIEWED: 'RESOURCE_VIEWED',
  RESOURCE_COMPLETED: 'RESOURCE_COMPLETED',
  BOOKMARK_ADDED: 'BOOKMARK_ADDED',
  FAVORITE_ADDED: 'FAVORITE_ADDED',
  NOTE_CREATED: 'NOTE_CREATED',
  COLLECTION_CREATED: 'COLLECTION_CREATED',
  REVISION_COMPLETED: 'REVISION_COMPLETED',
};

export const INSIGHT_TYPES = {
  PROGRESS: 'PROGRESS',
  CONSISTENCY: 'CONSISTENCY',
  WARNING: 'WARNING',
  ACHIEVEMENT: 'ACHIEVEMENT',
};

export const PRIORITY_LEVELS = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

// Standardized learning flow progression
export const LEARNING_STAGES = {
  LECTURE: 1,
  NOTES: 2,
  PRACTICE: 3,
  EXERCISE: 4,
  PYQS: 5,
  CHALLENGE: 6,
  REVISION: 7,
};

// Reusable function to calculate Priority String from a 0-100 Score
export const getPriorityFromScore = (score) => {
  if (score >= 80) return PRIORITY_LEVELS.HIGH;
  if (score >= 50) return PRIORITY_LEVELS.MEDIUM;
  return PRIORITY_LEVELS.LOW;
};
